global:
  tlsDisable: false
  openshift: true

server:
  route:
    enabled: true
    host: ${VAULT_DOMAIN}
  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/var/run/secrets/kubernetes.io/certs/tls.crt"
        tls_key_file = "/var/run/secrets/kubernetes.io/certs/tls.key"
      }
      storage "file" {
        path = "/vault/data"
      }
  ha:
    enabled: false
ui:
  enabled: true
